### ISSUE TITLE
@shopify/cypress-graphql is listed in the public npm repository

### ISSUE THREAD

**Issue by davebenvenuti** [Shopify/cypress-graphql#2]
# Issue summary

https://www.npmjs.com/package/@shopify/cypress-graphql

I noticed the repository is private, so I thought you might want to know the npm package appears publicly on npmjs.com.  If this is known or intentional, sorry to bother you!

## Expected behavior

I shouldn't see `@shopify/cypress-graphql` on npmjs.com

## Actual behavior

I see `@shopify/cypress-graphql` on npmjs.com

**Comment by RcKeller** [comment]
Not an issue. We have open sourced this previously internal project, and are [endorsed by Cypress](https://github.com/cypress-io/cypress-documentation/pull/4653).
